language: node_js
node_js:
  - 10.19.0
notifications:
  - matheus.teste0318@gmail.com
before_install:
  - npm install -g bower@1.3
  - npm install -g grunt-cli@0.1
  - npm install -g karma-cli@2.0
  - npm install -g protractor@1.5
  - webdriver-manager update
  - bower install
before_script:
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run -browsers PhantomJS